#!/bin/bash

set -e

echo "Building a development Docker image"
docker build -t ts-npm-package-starter .

[[ $# -eq 0 ]] && cmd="bash" || cmd="$@"
echo "Running ${cmd} in the development container"
docker run --rm -it \
    -v /app/node_modules \
    -v "$(pwd)":/app \
    -p 3000:3000 \
    ts-npm-package-starter \
    $cmd
