#!/bin/bash

set -e

TARGET_PROJECT=$1

if [[ ! -d "$TARGET_PROJECT" ]]; then
    echo "ERROR: Required arg, TARGET_PROJECT, was not provided."
    echo "Example usage: ./scripts/link-local-project /Users/jdoe/projects/FRED-studio-spa"
    echo "Exiting with status 1"
    exit 1
fi

echo "building and packaging the project"
npm run build
ZIP_PACKAGE_NAME=$(npm pack | tail -n 1)

echo "Removing local build from $TARGET_PROJECT"
rm -rf "$TARGET_PROJECT"/node_modules/@epistemix/spa-core/*

echo "Unpacking local build to $TARGET_PROJECT"
tar -xf "$ZIP_PACKAGE_NAME"
cp -r ./package/* "$TARGET_PROJECT"/node_modules/@epistemix/spa-core/

echo "Cleaning up"
rm -rf package
rm -f "$ZIP_PACKAGE_NAME"

echo "Success: $TARGET_PROJECT now contains a local build of @epistemix/spa-core"
