#!/bin/bash

set -e

: "${NPM_TOKEN:?Required NPM_TOKEN env var is not set - exiting.}"
: "${VERSION:?Required VERSION env var is not set - exiting.}"

echo "Verifying and building code"
NODE_ENV=production ./scripts/build-and-verify-code

echo "Publishing to npm registry as a public package"
npm publish --access public

echo "Success: Published version ${VERSION}"
