#!/bin/bash

set -e

TARGET_PROJECT=$1

if [[ ! -d "$TARGET_PROJECT" ]]; then
    echo "ERROR: Required arg, TARGET_PROJECT, was not provided."
    echo "Example usage: ./scripts/unlink-local-project /Users/jdoe/projects/FRED-studio-spa"
    echo "Exiting with status 1"
    exit 1
fi

echo "Removing local build of @epistemix/spa-core from $TARGET_PROJECT"
(
    cd "$TARGET_PROJECT" || exit 1
    rm -rf "$TARGET_PROJECT"/node_modules/@epistemix/spa-core
    npm install
)

echo "Success: local build of @epistemix/spa-core removed from $TARGET_PROJECT"
