name: "Main Push Actions"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish_a_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Check for changes in the src dir
        id: src-code-changes
        uses: tj-actions/changed-files@v18.7
        with:
          files: src/*

      - name: Verify the requested version is unique
        if: steps.src-code-changes.outputs.any_changed == 'true'
        env:
          VERSION: ${{ steps.package-version.outputs.current-version}}
        run: ./scripts/verify-version-is-unique

      - name: Build and publish the library
        if: steps.src-code-changes.outputs.any_changed == 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.package-version.outputs.current-version}}
        run: ./scripts/ci ./scripts/publish

      - name: Tag code and push to GitHub
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.package-version.outputs.current-version}}
          message: 'Tagging as version ${{ steps.package-version.outputs.current-version}}'
