name: "Main PR Actions"

on:
  pull_request:
    branches:
      - main

jobs:
  pre_release_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Check for changes in the src dir
        id: src-code-changes
        uses: tj-actions/changed-files@v18.7
        with:
          files: src/*

      - name: "Verify the requested version is unique"
        if: steps.src-code-changes.outputs.any_changed == 'true'
        env:
          VERSION: ${{ steps.package-version.outputs.current-version}}
        run: ./scripts/verify-version-is-unique

      - name: "Run code quality checks"
        env:
          RT_NPM_AUTH_TOKEN: ${{ secrets.RT_NPM_AUTH_TOKEN }}
        run: ./scripts/ci ./scripts/build-and-verify-code
